server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankus_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

